services:

  db:
    image: mariadb:12.3.2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: books
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:4.3.2-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: . 
    ports:
      - "8010:8010"
    depends_on:
      - db
      - rabbitmq
    environment:
      DB_DSN: "user:password@tcp(db:3306)/books?parseTime=true"
      RABBITMQ_URL: "amqp://user:password@rabbitmq:5672/"
